export {
  fetchCategories,
  fetchJobWorks,
  fetchProducts,
  fetchVendors,
  fetchReceipts,
  fetchDispatches,
  fetchPayments,
  fetchActivityLogs,
  fetchReferences,
  fetchSharedVariants,
  saveVendor,
  saveCategory,
  saveProduct,
  saveJobWork,
  saveDispatch,
  saveReceipt,
  savePayment,
  saveActivityLog,
  saveReference,
  saveSharedVariant,
  deleteReferenceRecord,
  deleteSharedVariantRecord,
  createVendor,
  createReceipt,
} from './supabaseClient';
